{
 "title": "Jitsi stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "jvbHost", "label": "videobridge Host", "query": "metrics.jitsi.*" }
  ]
 },
 "panels": [
  {
   "title": "Conferences",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.conferences"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.participants"
    }
   ]
  },
  {
   "title": "Largest conference",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.largest_conference"
    }
   ]
  },
  {
   "title": "Videostreams",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.videostreams"
    }
   ]
  },
  {
   "title": "Audiochannels",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.audiochannels"
    }
   ]
  },
  {
   "title": "Download",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.bit_rate_download"
    }
   ]
  },
  {
   "title": "Total conferences completed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.total_conferences_completed"
    }
   ]
  },
  {
   "title": "Videochannels",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.videochannels"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 3 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.bit_rate_upload"
    }
   ]
  },
  {
   "title": "Total conferences time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.total_conference_seconds"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.jitter_aggregate"
    }
   ]
  },
  {
   "title": "Loss rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.loss_rate_download"
    }
   ]
  },
  {
   "title": "RTT",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.rtt_aggregate"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.cpu_usage"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 6 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.used_memory"
    }
   ]
  },
  {
   "title": "Java threads",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "metrics.jitsi.$jvbHost.threads" }
   ]
  },
  {
   "title": "Jitter",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.jitter_aggregate"
    }
   ]
  },
  {
   "title": "Loss rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "metrics.jitsi.$jvbHost.loss_rate_download"
    }
   ]
  }
 ]
}